ALTER TABLE CITYTRUCK.SG_EGRESOS
 DROP PRIMARY KEY CASCADE;

DROP TABLE CITYTRUCK.SG_EGRESOS CASCADE CONSTRAINTS;

CREATE TABLE CITYTRUCK.SG_EGRESOS
(
  ID_EGRESO   NUMBER(7)                         NOT NULL,
  NRO_COMP    NUMBER(7)                         NOT NULL,
  FECHA       DATE                              NOT NULL,
  REGISTRAR   VARCHAR2(40 BYTE)                 NOT NULL,
  CONCEPTO    VARCHAR2(140 BYTE)                NOT NULL,
  ID_CAJA     NUMBER(7)                         NOT NULL,
  IMPORTE     NUMBER(15,5)                      NOT NULL,
  ID_USUARIO  NUMBER(5)                         NOT NULL,
  FECHA_REG   DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CITYTRUCK.SG_EGRESOS_PK ON CITYTRUCK.SG_EGRESOS
(ID_EGRESO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE CITYTRUCK.SG_EGRESOS ADD (
  CONSTRAINT SG_EGRESOS_PK
  PRIMARY KEY
  (ID_EGRESO)
  USING INDEX CITYTRUCK.SG_EGRESOS_PK
  ENABLE VALIDATE);

ALTER TABLE CITYTRUCK.SG_EGRESOS ADD (
  CONSTRAINT SG_EGRESOS_R01 
  FOREIGN KEY (ID_CAJA) 
  REFERENCES CITYTRUCK.SG_CAJAS (ID_CAJA)
  ENABLE VALIDATE);
