INSERT INTO CITYTRUCK.SG_MENU_OPCIONES (ID_OPC, OPCION, LINK, TOOLTIP, ICONO, ESTILO, ID_PADRE, ESTADO, ORDEN)
VALUES(9,'Consumo Propio','App.View.ConsumoPropio.Principal','Modulo de Consumo Propio','application_add','','','A',6);

INSERT INTO CITYTRUCK.SG_PERFILES_OPCIONES (ID_PRF_OPC, ID_PERFIL, ID_OPC, ESTADO)
VALUES(10,1,9, 'A');

COMMIT;