ALTER TABLE CITYTRUCK.SG_CONSUMOS
 DROP PRIMARY KEY CASCADE;

DROP TABLE CITYTRUCK.SG_CONSUMOS CASCADE CONSTRAINTS;

CREATE TABLE CITYTRUCK.SG_CONSUMOS
(
  ID_CONSUMO      NUMBER(7)                     NOT NULL,
  ID_COMBUSTIBLE  NUMBER(5)                     NOT NULL,
  ID_CLIENTE      NUMBER(7)                     NOT NULL,
  NRO_COMP        NUMBER(7)                     NOT NULL,
  FECHA           DATE                          NOT NULL,
  TURNO           VARCHAR2(40 BYTE)             NOT NULL,
  PRECIO          NUMBER(15,5)                  NOT NULL,
  IMPORTE_BS      NUMBER(15,5)                  NOT NULL,
  IMPORTE_LTS     NUMBER(15,5)                  NOT NULL,
  RESPONSABLE     VARCHAR2(250 BYTE),
  ID_USUARIO      NUMBER(5)                     NOT NULL,
  FECHA_REG       DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CITYTRUCK.SG_CONSUMOS_PK ON CITYTRUCK.SG_CONSUMOS
(ID_CONSUMO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CITYTRUCK.SG_CONSUMOS ADD (
  CONSTRAINT SG_CONSUMOS_PK
 PRIMARY KEY
 (ID_CONSUMO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE CITYTRUCK.SG_CONSUMOS ADD (
  CONSTRAINT SG_CONSUMOS_R01 
 FOREIGN KEY (ID_COMBUSTIBLE) 
 REFERENCES CITYTRUCK.SG_COMBUSTIBLES (ID_COMBUSTIBLE),
  CONSTRAINT SG_CONSUMOS_R02 
 FOREIGN KEY (ID_CLIENTE) 
 REFERENCES CITYTRUCK.SG_CLIENTES_CONSUMO (ID_CLIENTE));
SET DEFINE OFF;
Insert into CITYTRUCK.SG_CONSUMOS
   (ID_CONSUMO, ID_COMBUSTIBLE, ID_CLIENTE, NRO_COMP, FECHA, 
    TURNO, PRECIO, IMPORTE_BS, IMPORTE_LTS, RESPONSABLE, 
    ID_USUARIO, FECHA_REG)
 Values
   (1, 1, 6, 1, TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'DIA', 3.74, 82.28, 22, 'SADASDASD', 
    2, TO_DATE('01/24/2014 23:44:53', 'MM/DD/YYYY HH24:MI:SS'));
Insert into CITYTRUCK.SG_CONSUMOS
   (ID_CONSUMO, ID_COMBUSTIBLE, ID_CLIENTE, NRO_COMP, FECHA, 
    TURNO, PRECIO, IMPORTE_BS, IMPORTE_LTS, RESPONSABLE, 
    ID_USUARIO, FECHA_REG)
 Values
   (2, 2, 4, 2, TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'DIA', 3.72, 111.6, 30, 'ADSDASD', 
    2, TO_DATE('01/24/2014 23:51:31', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
