ALTER TABLE CITYTRUCK.SG_CLIENTES_CONSUMO
 DROP PRIMARY KEY CASCADE;

DROP TABLE CITYTRUCK.SG_CLIENTES_CONSUMO CASCADE CONSTRAINTS;

CREATE TABLE CITYTRUCK.SG_CLIENTES_CONSUMO
(
  ID_CLIENTE   NUMBER(7)                        NOT NULL,
  CODIGO       NUMBER(7)                        NOT NULL,
  NOMBRE       VARCHAR2(40 BYTE)                NOT NULL,
  RESPONSABLE  VARCHAR2(150 BYTE),
  CONSUMO      NUMBER(15,5),
  ID_USUARIO   NUMBER(5)                        NOT NULL,
  FECHA_REG    DATE,
  CONSUMO_BS   NUMBER(15,5)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CITYTRUCK.SG_CLIENTES_CONSUMO_PK ON CITYTRUCK.SG_CLIENTES_CONSUMO
(ID_CLIENTE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CITYTRUCK.SG_CLIENTES_CONSUMO ADD (
  CONSTRAINT SG_CLIENTES_CONSUMO_PK
 PRIMARY KEY
 (ID_CLIENTE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
SET DEFINE OFF;
Insert into CITYTRUCK.SG_CLIENTES_CONSUMO
   (ID_CLIENTE, CODIGO, NOMBRE, RESPONSABLE, CONSUMO, 
    ID_USUARIO, FECHA_REG, CONSUMO_BS)
 Values
   (5, 2002, 'RUFINO MERCADO - GASOLINA', 'RUFINO MERCADO', 0, 
    2, TO_DATE('01/24/2014 23:26:46', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into CITYTRUCK.SG_CLIENTES_CONSUMO
   (ID_CLIENTE, CODIGO, NOMBRE, RESPONSABLE, CONSUMO, 
    ID_USUARIO, FECHA_REG, CONSUMO_BS)
 Values
   (6, 2003, 'ROLY MERCADO - GASOLINA', 'ROLY MERCADO', 0, 
    2, TO_DATE('01/24/2014 23:27:05', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into CITYTRUCK.SG_CLIENTES_CONSUMO
   (ID_CLIENTE, CODIGO, NOMBRE, RESPONSABLE, CONSUMO, 
    ID_USUARIO, FECHA_REG, CONSUMO_BS)
 Values
   (4, 2001, 'RUFINO MERCADO - DIESEL', 'RUFINO MERCADO', 0, 
    2, TO_DATE('01/24/2014 23:26:33', 'MM/DD/YYYY HH24:MI:SS'), 0);
COMMIT;
