INSERT INTO CITYTRUCK.SG_MENU_OPCIONES (ID_OPC, OPCION, LINK, TOOLTIP, ICONO, ESTILO, ID_PADRE, ESTADO, ORDEN)
VALUES(10,'Tanques','App.View.Tanques.Principal','Modulo de administracion de Tanques','application_add','','','A',8);

INSERT INTO CITYTRUCK.SG_PERFILES_OPCIONES (ID_PRF_OPC, ID_PERFIL, ID_OPC, ESTADO)
VALUES(11,1,10, 'A');

COMMIT;