INSERT INTO CITYTRUCK.SG_MENU_OPCIONES (ID_OPC, OPCION, LINK, TOOLTIP, ICONO, ESTILO, ID_PADRE, ESTADO, ORDEN)
VALUES(7,'Otros Egresos','App.View.Egresos.Principal','Modulo de Otros Egresos','application_add','','','A',4);

INSERT INTO CITYTRUCK.SG_PERFILES_OPCIONES (ID_PRF_OPC, ID_PERFIL, ID_OPC, ESTADO)
VALUES(8,1,7, 'A');

COMMIT;