INSERT INTO CITYTRUCK.SG_MENU_OPCIONES (ID_OPC, OPCION, LINK, TOOLTIP, ICONO, ESTILO, ID_PADRE, ESTADO, ORDEN)
VALUES(8,'Cuentas por Cobrar','App.View.CuentasPC.Principal','Modulo de Cuentas Por Cobrar','application_add','','','A',5);

INSERT INTO CITYTRUCK.SG_PERFILES_OPCIONES (ID_PRF_OPC, ID_PERFIL, ID_OPC, ESTADO)
VALUES(9,1,8, 'A');

COMMIT;