ALTER TABLE CITYTRUCK.SG_AJUSTE_PRECIO
 DROP PRIMARY KEY CASCADE;

DROP TABLE CITYTRUCK.SG_AJUSTE_PRECIO CASCADE CONSTRAINTS;

CREATE TABLE CITYTRUCK.SG_AJUSTE_PRECIO
(
  ID_AJUSTE       NUMBER(7)                     NOT NULL,
  ID_COMBUSTIBLE  NUMBER(5)                     NOT NULL,
  FECHA_ALTA      DATE                          NOT NULL,
  FECHA_BAJA      DATE,
  TIPO            VARCHAR2(250 BYTE)            NOT NULL,
  PRECIO          NUMBER(15,5)                  NOT NULL,
  ID_USUARIO      NUMBER(5)                     NOT NULL,
  ESTADO          VARCHAR2(1 BYTE)              NOT NULL,
  FECHA_REG       DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CITYTRUCK.SG_AJUSTE_PRECIO_PK ON CITYTRUCK.SG_AJUSTE_PRECIO
(ID_AJUSTE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CITYTRUCK.SG_AJUSTE_PRECIO ADD (
  CONSTRAINT SG_AJUSTE_PRECIO_PK
 PRIMARY KEY
 (ID_AJUSTE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE CITYTRUCK.SG_AJUSTE_PRECIO ADD (
  CONSTRAINT SG_AJUSTE_PRECIO_R01 
 FOREIGN KEY (ID_COMBUSTIBLE) 
 REFERENCES CITYTRUCK.SG_COMBUSTIBLES (ID_COMBUSTIBLE));
SET DEFINE OFF;
Insert into CITYTRUCK.SG_AJUSTE_PRECIO
   (ID_AJUSTE, ID_COMBUSTIBLE, FECHA_ALTA, FECHA_BAJA, TIPO, 
    PRECIO, ID_USUARIO, ESTADO, FECHA_REG)
 Values
   (1, 1, TO_DATE('01/13/2014 22:56:39', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'VENTA', 
    3.74, 1, 'A', TO_DATE('01/13/2014 22:56:53', 'MM/DD/YYYY HH24:MI:SS'));
Insert into CITYTRUCK.SG_AJUSTE_PRECIO
   (ID_AJUSTE, ID_COMBUSTIBLE, FECHA_ALTA, FECHA_BAJA, TIPO, 
    PRECIO, ID_USUARIO, ESTADO, FECHA_REG)
 Values
   (2, 2, TO_DATE('01/13/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'VENTA', 
    3.72, 1, 'A', TO_DATE('01/13/2014 22:57:16', 'MM/DD/YYYY HH24:MI:SS'));
Insert into CITYTRUCK.SG_AJUSTE_PRECIO
   (ID_AJUSTE, ID_COMBUSTIBLE, FECHA_ALTA, FECHA_BAJA, TIPO, 
    PRECIO, ID_USUARIO, ESTADO, FECHA_REG)
 Values
   (3, 1, TO_DATE('01/13/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'COMPRA', 
    3.52, 1, 'A', TO_DATE('01/13/2014 22:59:59', 'MM/DD/YYYY HH24:MI:SS'));
Insert into CITYTRUCK.SG_AJUSTE_PRECIO
   (ID_AJUSTE, ID_COMBUSTIBLE, FECHA_ALTA, FECHA_BAJA, TIPO, 
    PRECIO, ID_USUARIO, ESTADO, FECHA_REG)
 Values
   (4, 2, TO_DATE('01/13/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'COMPRA', 
    3.54, 1, 'A', TO_DATE('01/13/2014 23:01:38', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
