ALTER TABLE CITYTRUCK.SG_CLIENTE_CONSUMO_COMBUSTIBLE
 DROP PRIMARY KEY CASCADE;

DROP TABLE CITYTRUCK.SG_CLIENTE_CONSUMO_COMBUSTIBLE CASCADE CONSTRAINTS;

CREATE TABLE CITYTRUCK.SG_CLIENTE_CONSUMO_COMBUSTIBLE
(
  ID_TABLA        NUMBER(7)                     NOT NULL,
  ID_CLIENTE      NUMBER(7),
  ID_COMBUSTIBLE  NUMBER(5),
  CLIENTE         VARCHAR2(250 BYTE),
  COMBUSTIBLE     VARCHAR2(250 BYTE),
  CONSUMO         NUMBER(15,5),
  CONSUMO_BS      NUMBER(15,5)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CITYTRUCK.SG_CLIENTE_CONSUMO_COMBUSTI_PK ON CITYTRUCK.SG_CLIENTE_CONSUMO_COMBUSTIBLE
(ID_TABLA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CITYTRUCK.SG_CLIENTE_CONSUMO_COMBUSTIBLE ADD (
  CONSTRAINT SG_CLIENTE_CONSUMO_COMBUSTI_PK
 PRIMARY KEY
 (ID_TABLA)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
SET DEFINE OFF;
Insert into CITYTRUCK.SG_CLIENTE_CONSUMO_COMBUSTIBLE
   (ID_TABLA, ID_CLIENTE, ID_COMBUSTIBLE, CLIENTE, COMBUSTIBLE, 
    CONSUMO, CONSUMO_BS)
 Values
   (61, 5, 1, 'RUFINO MERCADO', 'GASOLINA', 
    NULL, NULL);
Insert into CITYTRUCK.SG_CLIENTE_CONSUMO_COMBUSTIBLE
   (ID_TABLA, ID_CLIENTE, ID_COMBUSTIBLE, CLIENTE, COMBUSTIBLE, 
    CONSUMO, CONSUMO_BS)
 Values
   (62, 5, 2, 'RUFINO MERCADO', 'DIESEL', 
    NULL, NULL);
Insert into CITYTRUCK.SG_CLIENTE_CONSUMO_COMBUSTIBLE
   (ID_TABLA, ID_CLIENTE, ID_COMBUSTIBLE, CLIENTE, COMBUSTIBLE, 
    CONSUMO, CONSUMO_BS)
 Values
   (63, 6, 1, 'ROLY MERCADO', 'GASOLINA', 
    NULL, NULL);
Insert into CITYTRUCK.SG_CLIENTE_CONSUMO_COMBUSTIBLE
   (ID_TABLA, ID_CLIENTE, ID_COMBUSTIBLE, CLIENTE, COMBUSTIBLE, 
    CONSUMO, CONSUMO_BS)
 Values
   (64, 6, 2, 'ROLY MERCADO', 'DIESEL', 
    23, 85.56);
Insert into CITYTRUCK.SG_CLIENTE_CONSUMO_COMBUSTIBLE
   (ID_TABLA, ID_CLIENTE, ID_COMBUSTIBLE, CLIENTE, COMBUSTIBLE, 
    CONSUMO, CONSUMO_BS)
 Values
   (65, 4, 1, 'RUFINO MERCADO', 'GASOLINA', 
    14, 52.36);
Insert into CITYTRUCK.SG_CLIENTE_CONSUMO_COMBUSTIBLE
   (ID_TABLA, ID_CLIENTE, ID_COMBUSTIBLE, CLIENTE, COMBUSTIBLE, 
    CONSUMO, CONSUMO_BS)
 Values
   (66, 4, 2, 'RUFINO MERCADO', 'DIESEL', 
    2224545, 8275307.4);
COMMIT;
