ALTER TABLE CITYTRUCK.SG_COMBUSTIBLES
 DROP PRIMARY KEY CASCADE;

DROP TABLE CITYTRUCK.SG_COMBUSTIBLES CASCADE CONSTRAINTS;

CREATE TABLE CITYTRUCK.SG_COMBUSTIBLES
(
  ID_COMBUSTIBLE   NUMBER(5)                    NOT NULL,
  NOMBRE           VARCHAR2(40 BYTE)            NOT NULL,
  DESCRIPCION      VARCHAR2(150 BYTE)           NOT NULL,
  CANT_DISPONIBLE  NUMBER(15,5)                 NOT NULL,
  PRECIO_VENTA     NUMBER(15,5),
  PRECIO_COMPRA    NUMBER(15,5),
  UNIDAD           VARCHAR2(40 BYTE)            NOT NULL,
  ESTADO           CHAR(1 BYTE)                 NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CITYTRUCK.SG_COMBUSTIBLES_PK ON CITYTRUCK.SG_COMBUSTIBLES
(ID_COMBUSTIBLE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CITYTRUCK.SG_COMBUSTIBLES ADD (
  CONSTRAINT SG_COMBUSTIBLES_PK
 PRIMARY KEY
 (ID_COMBUSTIBLE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
SET DEFINE OFF;
Insert into CITYTRUCK.SG_COMBUSTIBLES
   (ID_COMBUSTIBLE, NOMBRE, DESCRIPCION, CANT_DISPONIBLE, PRECIO_VENTA, 
    PRECIO_COMPRA, UNIDAD, ESTADO)
 Values
   (1, 'GASOLINA', 'GASOLINA OIL', 0, 3.74, 
    3.52, 'LITROS', 'A');
Insert into CITYTRUCK.SG_COMBUSTIBLES
   (ID_COMBUSTIBLE, NOMBRE, DESCRIPCION, CANT_DISPONIBLE, PRECIO_VENTA, 
    PRECIO_COMPRA, UNIDAD, ESTADO)
 Values
   (2, 'DIESEL', 'DIESEL', 0, 3.72, 
    3.54, 'LITROS', 'A');
COMMIT;
